### ISSUE TITLE
How to modify and generate the styles fill pattern ?

### ISSUE THREAD

**Issue by johnnylc** [geostyler/geostyler-openlayers-parser#228]
# Question
I am using geostyler-openlayers-parser to render GeoJson in vector layer. In the GeoStyler's online demo, for the style kind: "Fill" there exist the option "Graphic Fill", but it will not work either in your online demo or my project. 
So how to modify the fill pattern of the style using geostyler-openlayers-parser?

![image](https://user-images.githubusercontent.com/12717523/81499743-52673500-9300-11ea-86a8-d774ae9380cc.png)

**Comment by jansule** [comment]
In contrast to the geostyler-sld-parser, the geostyler-openlayers-parser does not yet support fill patterns. So fill pattern changes in the UI are not reflected in the openlayers style.

You are more than welcome to provide a PR that implements that feature.

**Comment by johnnylc** [comment]
Ok, thanks.
