### ISSUE TITLE
Allow Parser to return no Outline for Fill symbolizers

### ISSUE THREAD

**Issue by iltapommi** [geostyler/geostyler-openlayers-parser#229]
# Feature Request

Currently the OlStyleParser returns a Stroke for all FillSymbolizers even if outlinewidth and/or outlinecolor are undefined. Fill color is returned only if a color is defined, but the same approach is not applied to outlines. Thus, polygon styles without outline don't seem to work, but rather always draw a default outline.

Currently for the fill it is checked if symbolizer.color is present and an OlStyleFillConstructor is returned if so. 

`  getOlPolygonSymbolizerFromFillSymbolizer(symbolizer: FillSymbolizer) {
    const fill = symbolizer.color ? new this.OlStyleFillConstructor({
      color: (symbolizer.color && symbolizer.opacity !== null && symbolizer.opacity !== undefined) ?
        OlStyleUtil.getRgbaColor(symbolizer.color, symbolizer.opacity) : symbolizer.color
    }) : null;
    return new this.OlStyleConstructor({
      stroke: new this.OlStyleStrokeConstructor({
        color: symbolizer.outlineColor,
        width: symbolizer.outlineWidth
      }),
      fill: fill
    });
  }`

Is there any reason why the same couldn't be applied to OlStyleStrokeConstructur, i.e. 
`const stroke = symbolizer.outlineColor || symbolizer.outlineWidth ? return new this.OlStyleStrokeConstructor({...}) : null ` ?

Of course polygons without outlines don't always render nicely (a better approach is often to use strokes with 0 width and same colour as the fill, but in some cases drawing no outline/stroke can be prefered.

**Comment by jansule** [comment]
Thanks for the info @iltapommi.

I agree with you. An outline is not a technical requirement for a fill style. Therefore, it should be optional and no default should be set.

> Of course polygons without outlines don't always render nicely (a better approach is often to use strokes with 0 width and same colour as the fill)

True. This is something a user has to decide/explore, and should not be restricted by our code.

Would you be willing to provide a PR for that?

**Comment by iltapommi** [comment]
That just by itself should be a pretty straightforward thing to implement and will try to have a look at it. But I think there are other issues that would need resolving or at least some scrutiny as well. For instance, currently only width and color can be passed to a OlPolygonSymbolizerFromFillSymbolizer, instead all possible props of getOlLineSymbolizerFromLineSymbolizer, such as dash-arrays, etc. 

Therefore, if one currently wants to build polygons with a dashed outline, separate symbolizers would need to be created, at least according to my interpretation. The current GeoStyler editor also doesn't provide this possibility, but manually writing a SLD PolygonSymbolizer with a Stroke child with e.g. dash properties, is translated to Geostyler properly, so seems to get interpreted properly (instead of writing separate PolygonSymbolizers and LineSymbolizers).

So I'm wondering if the right thing to do would be to add all properties like outlineOpacity, outlineDasharray etc. to the OlPolygonSymbolizerFromFillSymbolizer's Stroke element?

**Comment by jansule** [comment]
> That just by itself should be a pretty straightforward thing to implement and will try to have a look at it.

That's great. Thanks!

> But I think there are other issues that would need resolving or at least some scrutiny as well.

Could you add a work in progress (WIP) PR that contains tests that show the current parsing output versus the output you would expect for the mentioned cases? This will make it easier to discuss the specific parts in detail.

> Therefore, if one currently wants to build polygons with a dashed outline, separate symbolizers would need to be created, at least according to my interpretation. The current GeoStyler editor also doesn't provide this possibility

I'm not sure, if I understood this right, but it is possible to create multiple symbolizers for a single rule by clicking on the `add` button in the symbolizer window.

![image](https://user-images.githubusercontent.com/12186477/82826081-b6ffc380-9eac-11ea-8416-0cb44c820bb9.png)

> So I'm wondering if the right thing to do would be to add all properties like outlineOpacity, outlineDasharray etc. to the OlPolygonSymbolizerFromFillSymbolizer's Stroke element?

A WIP PR might facilitate discussing the specifics.
