### ISSUE TITLE
Support for font-based symbols in styles

### ISSUE THREAD

**Issue by jahow** [geostyler/geostyler-openlayers-parser#230]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Geoserver/Geotools offer support for many different kind of content in the `wellKnownName` attribute, including font glyphs using e.g. `ttf://Arial#0064` as a well known name.

The Geostyler OL parser already supports some geotools custom symbols starting with `shape://`, I would like to know if adding support for font glyphs would be of interest and in line with the project philosophy.

**Describe the solution you'd like**
Basically a new code branch would handle well-known names starting with `ttf://`, with the following process:
1. Extract the font name in the well known name
2. When creating the style, instead of adding an image style, add a text style with the given font and character to show the symbol
3. Optionally, check the font availability using the [Fonts API](https://developer.mozilla.org/en-US/docs/Web/API/Document/fonts) and throw an error otherwise

**Describe alternatives you've considered**
Without such support built into the parser, the only way to obtain glyph-based styles using it would be to add somewhere along the line a custom callback to handle the wellknown name and allow consumer projects to run custom logic.

Not much to add, thanks a lot for the geostyler project!

Edit: some reference from the GeoServer doc: https://docs.geoserver.org/stable/en/user/styling/sld/extensions/pointsymbols.html#bulk-ttf-marks

**Comment by KaiVolland** [comment]
I really like this idea.
And your proposal sounds straightforward to implement.
Maybe you can come up with a PR including a test with an input and output style.

**Comment by weskamm** [comment]
Just dropping this here as an inspiration: https://github.com/geostyler/geostyler/pull/1071
