### ISSUE TITLE
Dynamic point icon symbology based on feature attributes

### ISSUE THREAD

**Issue by raitisbe** [geostyler/geostyler-openlayers-parser#363]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Only one image can be applied for features in a layer. To have different icons, we need to either create multiple rules or have multiple layers for each image.

**Describe the solution you'd like**
Icon url should be decided based on feature attribute values and {{ templates }} in a similar way how the label for TextSymbolizer is created.

**Describe alternatives you've considered**
Walkaround is to create multiple rules and filters with one IconSymbolizer per each rule-filter pair.

**Additional context**

**Comment by jansule** [comment]
Thanks for your contribution @raitisbe. I like the idea. So that's +1 from my side.

**Comment by jansule** [comment]
Done in #364
