### ISSUE TITLE
Consistency across parsers for wellKnownName

### ISSUE THREAD

**Issue by geographika** [geostyler/geostyler-openlayers-parser#550]
Should the individual parsers have consistent functionality?

I was running through the example at https://github.com/geostyler/geostyler-sld-parser/blob/master/README.md for the SLD parser and it worked fine with the input `wellKnownName: "Circle"` (due to conversion to lower case [here](https://github.com/geostyler/geostyler-sld-parser/blob/88fe8756b014144a4667d7eb1d0d5c704c43e018/src/SldStyleParser.ts#L1875))

The [OpenLayers example](https://github.com/geostyler/geostyler-openlayers-parser/blob/master/README.md) however failed with  `wellKnownName: "Circle"` and only accepts lowercase. 

Should the OpenLayers parser be made to be more accepting? The SLD parser stricter, or is it ok to require different inputs?

**Comment by KaiVolland** [comment]
The correct style is only defined by the 'geostyler-style'. So 'Circle' ist definetly wrong.
Im not sure about how to deal with this but i guess only accepting the correct format would bei more parserlike and consistent.

**Comment by KaiVolland** [comment]
It seems like this was fixed in the `geosyler-sld-parser` already.
