### ISSUE TITLE
[openlayers-parser] Support named colors in `OlStyleUtil`

### ISSUE THREAD

**Issue by LukasLohoff** [geostyler/geostyler-openlayers-parser#551]
# Feature Request

Hi, would it be possible to support parsing named colors? 

Current behavior: If I parse the following openlayers style:

```js
const olStyle = new Style({
  stroke: new Stroke({
    color: 'blue',
    lineDash: [4],
    width: 3
  })
});
```

the color attribute will be ignored and the resulting geostyler style is:

```json
{
    "output": {
        "name": "OL Style",
        "rules": [
            {
                "name": "OL Style Rule 0",
                "symbolizers": [
                    {
                        "kind": "Line",
                        "width": 3,
                        "dasharray": [
                            4
                        ]
                    }
                ]
            }
        ]
    }
}
```

**Describe the solution you'd like**

Probably a simple lookup function would be enough. Alternatively a package like https://www.npmjs.com/package/colornames can be used. This also simply uses a lookup object.

What do you think, will this solution have any side effects / possible issues?

**Comment by marcjansen** [comment]
I think it is a valid assumption that a named color translates into sth equivalent in another format, so yes, I think we should support named colors and transform them to an internal fromat.

If we're sure we always have a DOM, than we could borrow [this method](https://github.com/openlayers/openlayers/blob/238695a107dfb22358f5c0f5a9e1efccd4c3c90a/src/ol/color.js#L51-L62) from OL. I am pretty sure we shouldn't use it, though.

If we want to use an external dependency (I think we should): My choice would be [color-name](https://www.npmjs.com/package/color-name), 127 Mio. people a week cannot be wrong …

My 2 ¢

**Comment by LukasLohoff** [comment]
Yes. Implemented with https://github.com/geostyler/geostyler-openlayers-parser/pull/562
