### ISSUE TITLE
Unsupported FillOpacity property of the MarkSymbolizer entity

### ISSUE THREAD

**Issue by pragmaeuge** [geostyler/geostyler-openlayers-parser#620]
# Question

Hi,
I noted that the "FillOpacity" property is marked as unsupported for MarkSymbolizer by this parser. 
I have easily added the support for it in order to use the exported SLD file from QGIS: the SLD parser generates this property. 
Would you like that I do a pull request or not?

Eugenio.

**Comment by jansule** [comment]
Hi @pragmaeuge 

:+1: from my side. Thanks. Looking forward to seeing your PR.

**Comment by KaiVolland** [comment]
This should be fixed with #667
